# Minecraft / Fabric
minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.16.14
fabric_version=0.92.12+1.20.1
mtr_file=libs/mtr-fabric-4.0.5-1.20.1.jar

# Mod
mod_version=0.1.0
maven_group=com.mtroa
archives_base_name=mtr-outerchange-allowed

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false















